apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-web-server
  labels:
    app: simple-http-web-server
spec:
  replicas: 3 # number of pods to run

  # !IMPORTANT! labels selector for Service
  selector:
    matchLabels:
      app: simple-http-web-server

  # Define how we update version of app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: simple-http-web-server
    spec:
      containers:
        - name: simple-http-web-server
          image: 0xsera/simple-http-web-server:v0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 310Mi
              cpu: 310m
          # health-check
          # readinessProbe: check if container is ready to serve traffic
          readinessProbe:
            httpGet:
              path: /
              port: 8090
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 1
          # check if container is alive
          livenessProbe:
            httpGet:
              path: /jakarta
              port: 8090
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
