# kubectl -n pnt apply -f service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-web-server-service
  labels:
    app: simple-http-web-server-service
spec:
  selector:
    app: simple-http-web-server
  type: LoadBalancer # default, can be NodePort, LoadBalancer, ExternalName
  ports:
    - protocol: TCP
      port: 8090 # port of service
      targetPort: 8090 # port of application/pod
      nodePort: 30000  # NodePort you want to expose