# values.yaml
app:
  name: simple-http-web-server

replicaCount: 3

image:
  repository: 0xsera/simple-http-web-server
  tag: v0.0
  pullPolicy: Always

deployment:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

service:
  type: LoadBalancer
  protocol: TCP
  port: 8090
  targetPort: 8090
  nodePort: 31000

resources:
  requests:
    memory: 300Mi
    cpu: 300m
  limits:
    memory: 310Mi
    cpu: 310m

readinessProbe:
  path: /
  successThreshold: 1
  failureThreshold: 3
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 1

livenessProbe:
  path: /jakarta
  successThreshold: 1
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 1